[package]
name = "orbiting_sand"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
debug = true

[dependencies]
ggegui = "0.3.7"
ggez = "0.9.3"
hashbrown = { version = "0.14.2", features = ["ahash", "rayon"] }
rayon = "1.8.0"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name    = "bench_main"
harness = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "daemon"
path = "scenes/fallingsand.rs"
