name: Deploy Docs to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    release:
        name: GitHub Pages
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v1

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                profile: minimal
                override: true
                components: rustfmt, rust-src

            - name: Install dependencies
              run: sudo apt-get install -y librust-alsa-sys-dev pkg-config libudev-dev

            - name: Build Documentation
              uses: actions-rs/cargo@v1
              with:
                command: doc
                args: --all --no-deps

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
                publish_branch: gh-pages